version: '3'
services:
  ml_service:
    restart: always
    image: ml
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/neptun/PycharmProjects/Pytorch-UNet/out:/out
    ports:
      - "5000:5000"
 
networks:
  default:
    driver: bridge
